services:
  glpi:
    image: glpi/glpi:latest
    restart: unless-stopped
    ports:
      - 5005:80
    volumes:
      - ./storage/glpi:/var/glpi:rw
    environment:
      GLPI_DB_HOST: ${GLPI_DB_HOST}
      GLPI_DB_PORT: ${GLPI_DB_PORT}
      GLPI_DB_NAME: ${GLPI_DB_NAME}
      GLPI_DB_USER: ${GLPI_DB_USER}
      GLPI_DB_PASSWORD: ${GLPI_DB_PASSWORD}
      GLPI_DB_ROOT_PASSWORD: ${GLPI_DB_ROOT_PASSWORD}
    depends_on:
      mysql:
        condition: service_healthy
  mysql:
    image: mysql:8.4.7
    restart: unless-stopped
    ports:
      - 3306:3306
    volumes:
      - ./storage/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${GLPI_DB_NAME}
      MYSQL_USER: ${GLPI_DB_USER}
      MYSQL_PASSWORD: ${GLPI_DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${GLPI_DB_ROOT_PASSWORD}
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s